"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const formatCurrency = (value = 0) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);

const buildId = () => Math.random().toString(16).slice(2, 8).toUpperCase();

export function generateQuotePDF(
  bike,
  selectedParts = [],
  quote = null,
  options = {},
) {
  const doc = new jsPDF();
  const now = new Date();
  const ownsBike = Boolean(options.ownsBike);
  const basePrice = ownsBike ? 0 : bike?.base_price || 0;
  const lineItems = quote?.line_items?.length
    ? quote.line_items
    : selectedParts.map((part) => ({
        name: part.name,
        category: part.category,
        weight_delta: part.weight_delta || 0,
        hp_delta: part.hp_delta || 0,
        price: part.price || 0,
      }));
  const partsTotal = lineItems.reduce((sum, item) => sum + (item.price || 0), 0);
  const grandTotal = basePrice + partsTotal;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(249, 115, 22);
  doc.text("MotoForge", 14, 20);

  doc.setFontSize(11);
  doc.setTextColor(160, 160, 160);
  doc.text("Custom Motorcycle Modification Quotation", 14, 28);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(40, 40, 40);
  doc.text(
    `Bike Model: ${bike?.brand || ""} ${bike?.name || "Custom Build"}`.trim(),
    14,
    42,
  );
  doc.text(`Date: ${now.toLocaleDateString("en-IN")}`, 14, 49);
  doc.text(`Build ID: ${buildId()}`, 14, 56);
  doc.text(
    `Ownership: ${ownsBike ? "Customer already owns bike" : "Bike included in quote"}`,
    14,
    63,
  );

  autoTable(doc, {
    startY: 73,
    head: [["Part Name", "Category", "Weight Change", "HP Change", "Price (INR)"]],
    body: lineItems.map((item) => [
      item.name,
      item.category,
      `${item.weight_delta > 0 ? "+" : ""}${Number(item.weight_delta || 0).toFixed(1)} kg`,
      `${item.hp_delta > 0 ? "+" : ""}${Number(item.hp_delta || 0).toFixed(1)} HP`,
      formatCurrency(item.price || 0),
    ]),
    styles: {
      fontSize: 10,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: [24, 24, 27],
      textColor: [255, 255, 255],
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
  });

  const summaryY = doc.lastAutoTable.finalY + 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(
    `${ownsBike ? "Owned Bike Credit" : "Base Price"}: ${
      ownsBike ? "Included by owner" : formatCurrency(basePrice)
    }`,
    14,
    summaryY,
  );
  doc.text(`Parts Total: ${formatCurrency(partsTotal)}`, 14, summaryY + 8);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(249, 115, 22);
  doc.text(`Grand Total: ${formatCurrency(grandTotal)}`, 14, summaryY + 20);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by MotoForge | motoforge.app", 14, 285);

  doc.save(`motoforge_quote_${now.getTime()}.pdf`);
}
